var esNuevo = false;
var deseaImprimir = false;
var aceptarDesc = (15 + 19 == 33);
var juan = "juan";
var juan2 = "juan";
var Iguales = (juan == juan2);
console.log("Este booleano es: ", Iguales);
console.log("Este booleano es: ", aceptarDesc);
var ambos = aceptarDesc && Iguales;
console.log("El resultado de los boolean son: ", ambos);
